version: "3.8"
services:
  frontend:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # コンテナサーバーのポート5000をホストサーバーのポート5001にマッピング
    # ブラウザからのアクセスには5001を使用することで5000にアクセスすることができる
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    command: ["flask", "run", "--host=0.0.0.0"]
