services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ${FRONTEND_CONTAINER_NAME}
    env_file: ./.env
    restart: always
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=${NODE_ENV}
    networks:
      - vex_app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ${BACKEND_CONTAINER_NAME}
    env_file: ./.env
    restart: always
    volumes:
      - ./backend:/app
      - /app/venv
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_RUN_HOST=${FLASK_RUN_HOST}
      - FLASK_RUN_PORT=${FLASK_RUN_PORT}
    command: ["flask", "run"]
    networks:
      - vex_app_network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/conf/vex_app.conf.temp:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./frontend/dist:/app/dist
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: always
    networks:
      - vex_app_network

networks:
  vex_app_network:
    name: vex_app_network
    driver: bridge
