#!/usr/bin/with-contenv sh
cp /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/vex_app.conf
sed -i -e "s/frontend/${FRONTEND_CONTAINER_NAME}/g" /etc/nginx/conf.d/vex_app.conf
sed -i -e "s/backend/${BACKEND_CONTAINER_NAME}/g" /etc/nginx/conf.d/vex_app.conf